use crate::cli::error::CliError;
use crate::cli::output::ExecutionContext;
use crate::orchestrator::proposal::{EvolutionProposal, ProposalKind, ProposalStatus, RiskLevel};
use std::time::{SystemTime, UNIX_EPOCH};

pub fn run(
    plan: Option<&str>,
    project: &str,
    dry_run: bool,
    ctx: &ExecutionContext,
) -> Result<(), CliError> {
    if dry_run {
        println!("Dry run mode: would evolve project at {project}");
        if let Some(p) = plan {
            println!("  Using plan: {p}");
        }
        return Ok(());
    }

    // Evolve is stub for v0.6.0 -- create an EvolutionProposal and save it
    let now_ms = SystemTime::now()
        .duration_since(UNIX_EPOCH)
        .unwrap_or_default()
        .as_millis() as i64;

    let proposal = EvolutionProposal {
        proposal_id: format!("ep_{now_ms}_evolve"),
        created_at: now_ms,
        source_task_id: "cli".to_string(),
        target: plan.unwrap_or("evolve").to_string(),
        kind: ProposalKind::CodeEdit,
        diff: None,
        rationale: "Generated by jishu evolve".to_string(),
        risk: RiskLevel::Medium,
        status: ProposalStatus::Draft,
    };

    // Save proposal
    let home = dirs::home_dir().ok_or_else(|| CliError::Internal("No home dir".to_string()))?;
    let proposals_dir = home.join(".jishu-hub").join("proposals");
    std::fs::create_dir_all(&proposals_dir).map_err(CliError::Io)?;
    let path = proposals_dir.join(format!("{}.json", proposal.proposal_id));
    let json = serde_json::to_string_pretty(&proposal).map_err(CliError::Serde)?;
    std::fs::write(&path, json).map_err(CliError::Io)?;

    if ctx.json {
        println!(
            "{}",
            serde_json::to_string(&proposal).map_err(CliError::Serde)?
        );
    } else {
        println!("Created proposal: {}", proposal.proposal_id);
        println!("  Status: Draft");
        println!("  Target: {}", proposal.target);
        println!("  Saved: {}", path.display());
    }

    Ok(())
}
